version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:${PORT}"
    volumes:
      - .:/app
      # - static_volume:/app/staticfiles
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
